theme: jekyll-theme-time-machine

remote_theme: pages-themes/leap-day@v0.2.0
plugins:
- jekyll-remote-theme

minify_html: false

lsi: false
safe: true
source: [your repo's top level directory]
incremental: true
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
