---
title: "Undergraduate/Graduate Research"
author: "Xiang Huang"
date: "`r Sys.Date()`"
output:
  tufte::tufte_html: 
    toc: true
  tufte::tufte_handout:
    citation_package: natbib
    latex_engine: xelatex
  tufte::tufte_book:
    citation_package: natbib
    latex_engine: xelatex
bibliography: skeleton.bib
link-citations: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

**"UIS is not known as a research school; it is a research school if you do your research there."**

My Ph.D. [advisor](https://jacklutz.com/) told me this when I was starting at UIS. I love sharing these words because they show that meaningful research can happen anywhere - you just need to make it happen. And UIS has proven to be just that kind of place, with great support for research and I am lucky to work with students who are eager to dive in.

For those who want to do research with me, I encourage you to read this page carefully to understand the requirements before we schedule a meeting.

## Time Commitment

Short answer: **Two semesters**. Ten to fifteen hours per week. I will meet with you weekly.

Time is the most valuable resource required in research, after perhaps interest. In general, I expect you to work **at least two semesters** with me. Please understand that time commitment applies both to you and to me. To "buy" you more time to do research, you are asked to take CSC 499: Tutorial to earn credits as an elective. Some students also do IPL 301 with me. 

I wish I can tell you that you can just work with me for a few weeks or a summer and then can have a shinny publication on your CV. But that is not the case. Not for the research I do. Not for the backgrounds my students usually have.

## Topics

Please find the (incomplete) list of topics on [this page](topics.html).

Generally, there are two types of topics.

-   Original research. The research I do to publish original/new results. It will usually require more effort from both you and me. And I will make sure I decompose meaningful tasks to get you engaged in the research.

-   Study topics. I have broad interests in theoretical computer science and mathematics. Every now and then there are topics that I want to *learn*. These type of topics can provide very good training for you as a undergraduate student or master student. These type of topics are called Senior Theses or Capstone Project in other institution, see for example [Jim Fix's (Reed College) topics](https://jimfix.github.io/research.html). Although we don't officially have Capstones in UIS, I want to do things along that line.

## Writing/Documenting

Once we start working on a project/topic. I expect you document your work at different stages (as code, report, slides, poster, video, paper). I will typically expect you present your work at [UIS STAR Symposium](https://www.uis.edu/research/student-research-support/student-technology-arts-research-symposium). It will be very helpful for your future job/graduate school application, and will be important for me to show off your work, too. **You will need to write a formal report using the LaTex template ( Chicago Math REU template) provided below.** Read the samples there to get an idea what the report should look like.

Below is a list of useful tools.

1.  [Notion](https://notion.so) for notes taking.
2.  LaTex for final paper/document.
  -   Use this template ([TEX](LaTex-template/TEMPLATE.tex)) ([PDF](LaTex-template/TEMPLATE.pdf)) for your final report.
  -   Visit [this site](https://math.vanderbilt.edu/bohmanar/latex.html) or [Chicago Math REU site](http://math.uchicago.edu/~may/REU2022/) for more information about LaTex and the format of final report I expect from you.
  - Use [Overleaf](https://www.overleaf.com/) or any LaTex editor you like. I personally use [Sublime Text](https://www.sublimetext.com/) + [LaTextools plugin](https://latextools.readthedocs.io/en/latest/).  
3.  I also use [R-Markdown](https://rmarkdown.rstudio.com/) to create webpages and notes.
4. Jupyter or Google CoLab or VS Code to write codes.
5. Use [GitHub](https://github.com/) and constantly commit to your repo to record things. 
6. Use [Mathcha](https://www.mathcha.io/) to draw pictures in Latex/Tikz. 

## Current Student(s) Advising
- Jarrin Peters (24Sm to now). Theorem proving via Lean in Chemical Reaction Network. 
- Austin Burden (24Sm to now). Population Protocol simulator.

## Past
- Praise Idowu (24Sm and 24F). Chemical Reaction Network and GPAC rewriting. 
- Christabel Bamigbade (24Sm). Lean theorem assistant. 
- Jonathan Miller (23Sm to 23F). Large Integer Multiplication Algorithms. I am proud to share his [survey paper](files/Mul_Survey.pdf) here.
- Anish Sinha (22Sp, 22Sm, to 23Sp). Chemical Reaction Network / Population Protocols simulation. 
His project “Concurrent B-Link-Trees and Its Applications in Database Systems: A Revisit”, won the best research product in the technology category in UIS Student Technology, Arts, & Research Symposium (STARS) 2023.
- Jared Robbins (22F to 23Sp): Quantum Computing and Mathematical Games.
- Rachel Huls (21Sm, 21F, and 22Sp). On large population protocol computable numbers. [Paper](https://arxiv.org/abs/2206.06594) published in DNA 28. 
- Eli Exner (21F). On normal number and finite automata. 
- Joseph Lolis (21F). On prime boolean matrices.
- Charlotte Medina (21Sp). On Champernowne's constant. 

## FAQs:
  
1. Can I get paid?
  <p style="margin-left: 30px">Every person who does his/her work should get paid. ~~But currently I don't have funding to support that belief.~~ (Now I have a [grant](https://www.uis.edu/news/two-uis-faculty-members-awarded-prestigious-doe-sc-grant-innovative-research-scientific) for the Chemical Reaction Networks related topics and I can pay you.)
  </p>  

2. Can I get a letter from you?
  <p style="margin-left: 30px">It is my job to write you a letter if you do research with me. In some sense, that is the only way I can write a meaningful letter for you. It will be hard for me to write a strong one for you if you exit in the middle. I will actually be reluctant in writing you a letter in this circumstance. </p>

3. How do I exit the project early?
  <p style="margin-left: 30px">Just tell me you want to leave. It will save both your time and mine this way. </p> 

4. How do I continue my research with you after a winter break or summer break? 
  <p style="margin-left: 30px">Just send me a letter to schedule regular meetings for the new semester. **I will not initiate that conversation.** I tried that before and only to learn that the students had already decided to leave. So I will assume if you don't contact me early in a semester, you're leaving.</p>
  
5. How many students do you mentor/advise every semester? 
<p style="margin-left: 30px">**Three**. I used to think I can advise every student approaching me. But I've learned my lesson.</p> 

6. Do you want a transcripts/CV/Cover Letter from me? Do I have to have a high GPA?
<p style="margin-left: 30px"> I need something that I can learn about you, whatever you believe that can help. Here is a [Twitter post](https://twitter.com/jbhuang0604/status/1627191986091438080?s=12&t=N3lPFCtR3BV7qWGTd_cCUw) that makes some useful suggestion in a funny way. A good GPA surely helps but that is not the only thing I will look into.</p>

7. Do you have any projects in Machine Learning? 
<p style="margin-left: 30px">No. I don't have any machine learning project currently. But that does not mean I won't have one in the future.</p>

8. Do I have to take credits from you?
<p style="margin-left: 30px">I would require that you take CSC 499: Tutorial. (Some students can also do IPL 300/301 (Internship) with me. Some even do both CSC 499 and IPL 300/301 with me.) That is a way that you can earn credits while doing research with me. More importantly, it buys you some time. You can take it as an elective and it counts towards graduation.  You typically have to have my approval to be able to register the course. </p>

9. I am an online student, can I do research with you?
<p style="margin-left: 30px">Of Course. Some of my best students are online students. You should definitely try if you are interested in working with me.</p>

10. I am an international student. Can I do research with you because my OPT is set to start on date X?
<p style="margin-left: 30px">
No, it is not a good idea to use research opportunities as a temporary transition. You need a considerable amount of time to build up the necessary knowledge before you can contribute to research, and I need to commit my time to help you. I cannot afford to invest my time knowing that you might leave very soon.
Although, as a former international student, I understand how important it is for you to have a "job" during your OPT, I don't feel it is right to help you just because of that. Research opportunities are for research purposes only.
</p>

11. What is the typical math background you expect from me?
<p style="margin-left: 30px">
I hope you have taken courses in Calculus I and II, Differential Equations, Discrete Math, and Algorithms. It would be ideal if you are a math student with a computer science minor or the other way around. However, I understand that my students at UIS may not always have the background I look for, but that does not mean we cannot build it along the way. I keep an open mind on this. The more important thing is your ability to learn new things.
</p>

